Feature/ServiceModalEdit (#12)
* Copy base of table page from Main screen

* Add Storybook

* Storybook typescript

* Add story of ServiceDetail screen

* Refactor reset styles location

* Apply global styles to Storybook

* Add useful Storybook addons

* Add test code
- most of them are similar with Main test

* Add Service details to ServiceDetail screen
- minor edit for interfaces

* change provider and context structure by adding ServiceModal things

* ServiceModal에 쓰이는 localization 추가

* ServiceModal 관련 shared & provider 추가 및 호출로직 구현

* Fix for snapshot

* add yup for formik

* remove console.log

* addd formik validation

* theme 연동

* Add more stories

* add localization

* add and modified types

* 서비스 추가 & 수정모드 modal 호출로직 추가 완료

* modify previewIconImage logic

* move code location of const vars

* add @testing-library/react-hooks

* update snapshot

* sync to 'feature/service-detail-screen'

* resolve error running jest

- "Cannot find module 'test-exclude' at Object.<anonymous> (mode_modules/babel-plugin-istanbul/lib/index.js:14:19)"
- installing 'test-exclude' on DevDependency resolve that errors

* append test code with attaching context API

* wrap providers in storybook index

to resolve compile error when 'Main' call Context API

* make ServiceModal less complex

- combining ServiceModalProvider with AppProvider
- remove ServiceModalProvider.js
- remove <ServiceModalProvider> wrapping from SwitchNavigator.tsx
- almost 90% coverage of test code of `ServiceModal`
- changed code style like `props.onAddServiceClick()` things inject to `Main` instead of using `serviceModalDispatch()` on Route Component(`Main` e.g.) directly

* update snapshot of `Intro`

* trying to trigger ServiceModal

* change codes for AppProvider testing

* remove unnecessary codes

* remove unncessary codes in test